#use_frameworks!
use_modular_headers!
platform :ios, '9.0'

target 'JJPDFViewer_Example' do
  pod 'JJPDFViewer', :path => '../'

  target 'JJPDFViewer_Tests' do
    inherit! :search_paths

    
  end
end
